### ISSUE TITLE
Imcompatibility with "Your Tokens visible"

### ISSUE THREAD

**Issue by SasaSuppenknecht** [MaterialFoundry/SharedVision#17]
The "Your Tokens visible" overwrites the settings of "SharedVision". Whatever it says for "TokenMultivision" is the used mode.

"Your tokens visible": https://foundryvtt.com/packages/TokensVisible

**Comment by MaterialFoundry** [comment]
I'm closing this since there hasn't been any activity for a long time and Your Tokens Visible still hasn't been updated for v10.
