### ISSUE TITLE
[BUG] libWrapper-warning with PDF-Pager active 

### ISSUE THREAD

**Issue by kagedansa** [MaterialFoundry/SharedVision#27]
**Setup**
 - OS: Windows
 - Browser: Foundry app
 - Module version: 1.1.2
 - Foundry version: 10.286
 - Any other modules enabled: yes

**Describe the bug**
There is a warning from libWrapper if PDF Pager is also active.

**Console Log**
![log](https://user-images.githubusercontent.com/110729103/194078602-99a4e418-0e30-4dee-8c07-c3cdb32bc1eb.png)

I'm not sure if it really causes problems, but a warning at least indicates that something is wrong.

**Comment by CDeenen** [comment]
I forgot to implement LibWrapper somewhere, I'll look into fixing that.
If this is causing a problem for Shared Vision, it'd result in the Vision Config not showing up or not functioning in the Actor directory (when you right-click an actor). I don't know what the effect could be on PDF Pager.

**Comment by farling42** [comment]
PDF Pager hooks into the _getEntryContextOptions function to add an extra option to the Actor and Item sidebar context menus. It is a function that is unlikely to be used by most users of the module now.

**Comment by MaterialFoundry** [comment]
This should be fixed in the latest release.
