### ISSUE TITLE
[BUG] Flickering vision during movement

### ISSUE THREAD

**Issue by adotor** [MaterialFoundry/SharedVision#29]
**Setup**
 - OS: Windows
 - Browser: Vialdi, Edge
 - Module version: 1.1.2
 - Foundry version: 10.291
 - Gaming system & version: dnd5e 2.0.3
 - Any other modules enabled: yes

**Describe the bug**
Configure a token that shares only Fog an Token with its owner.
Move the token. 
Expected: Token keeps vision when selected or after movement.

Issue: Full vision is lost after selection or movement via keyboard. Creates flickering when moving constantly.

**Console Log**
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'id')
[Detected 1 package: SharedVision]
    at revealTokenFog (misc.js:158:70)
    at revealAllFog (misc.js:212:9)
    at initializeSources (misc.js:82:3)
    at i.<anonymous> (socket.js:12:13)
    at x.emit (index.mjs:136:20)
    at i.value (socket.js:278:20)
    at i.value (socket.js:265:18)
    at i.value (socket.js:235:22)
    at x.emit (index.mjs:136:20)
    at s.value (manager.js:200:14)
    at x.emit (index.mjs:136:20)
    at a.value (index.js:119:51)
    at s.value (manager.js:192:22)
    at x.emit (index.mjs:136:20)
    at a.value (socket.js:323:26)
    at x.emit (index.mjs:136:20)
    at i.value (transport.js:104:14)
    at i.value (transport.js:97:14)
    at ws.onmessage (websocket.js:79:40)
```

**Comment by adotor** [comment]
I fixed the null issue, some tokens on the map had their actors removed. Still no change.

**Comment by adotor** [comment]
When dragging the token via mouse the full vision stays on after the token reached its destination.

**Comment by CDeenen** [comment]
Shared Vision was never meant to override the normal vision for selected tokens. The intended result would be more like this:
Say both token A and token B are owned by the player. Token B is set to share only fog, then when the player selects token A and token B would be moved by someone else, the fog would be updated. If the player then selects token B its vision should be normal (so with vision).
Based on that, the actual bug here is that token B loses vision when it's selected.

**Comment by adotor** [comment]
Maybe this happens when multiple settings are in effect.

I can reproduce this by applying following settings:
- Actor A is Owned by User X
- Actor B is Owned by User Y

Settings:
- Actor A and B are in Shared Global Vision
- Actor B Shares only Fog with User X

Logged in as User X, when User Y moves B the vision disappers.

When I change settings
- Token B Shares nothing with User B

Everything is fine.

Maybe something with the evaluation of multiple settings, e.g. are settings "merged" and the "most vision granting setting" wins?

**Comment by CDeenen** [comment]
> Logged in as User X, when User Y moves B the vision disappears/flickers.
This is not supposed to happen. If at that time User X has selected to token, the vision should be as normal. If User X doesn't have the token selected there should be no flicker and only the fog should be updated.
There were some changes in how vision is handled in the last Foundry update (or last 2 updates), it's possible that that broke something. I'll investigate it when I have the time.

**Comment by MaterialFoundry** [comment]
I'm closing this since there hasn't been any activity for a long time. Feel free to reopen it if it's still an issue.
