### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DaveydeHaas** [MaterialFoundry/SharedVision#35]
**Setup**
 - OS: [e.g. windows 10]
 - Browser: [Foundry app]
 - Module version: [e.g. 1.1.2]
 - Foundry version: [e.g. 12.325]
 - Gaming system & version: [e.g. dnd5e 3.20.0]
 - Any other modules enabled: [yes]

**Describe the bug**
Host gets stuck on token and only sees the vision of that token. If it sees another token you can click on that token it will add the vision off that token. It will never remove the old tokens vision.

**Console Log**
I am in a time need console logs and screenshots will be added later. Went back to foundry v11.315 where it still works.

**Additional context**

**Comment by jacksands** [comment]
I believe it is the same bug, it seems to be related with Global shared vision activated...  it do not allow to "deselect" the token by clicking anywhere, and any token with shared vision configured adds to the vision...

disabling   global shared vision stops the bug



https://github.com/CDeenen/SharedVision/assets/7229143/0471b023-2705-46b6-afb6-328f2aa2c192

**Comment by jacksands** [comment]
Also, just notice.. it also causes the ambient sounds to add...
sounds affecting different tokens still plays even if the token is deselected or global share is disable

**Comment by DaveydeHaas** [comment]
It is a workaround indeed. There is a loop if you do  it the wrong way around though so it would be even more entangeling. I hope there will be a definitive fix soon

**Comment by DaveydeHaas** [comment]
Another note not so great you need to turn on global shared vision every time in a specific matter to keep using global shared vision

**Comment by MaterialFoundry** [comment]
This should be fixed in the latest version

**Comment by DaveydeHaas** [comment]
Nice!!! everything works now, i just tested it
