### ISSUE TITLE
V12 upgrade, vision and ambient sound bugs

### ISSUE THREAD

**Issue by jacksands** [MaterialFoundry/SharedVision#37]
**Setup**
 - OS: windows 11
 - foudry vtt
 - Module version: v112
 - Foundry version: v12. 328
 - Gaming system & version: all tested, including last swade
 - Any other modules enabled: NO

**Describe the bug**
the vision and ambient sounds gets overlapped and deselect token becames useless 

**Screenshots**

I believe it is the same bug, it seems to be related with Global shared vision activated...  it do not allow to "deselect" the token by clicking anywhere, and any token with shared vision configured adds to the vision...

disabling   global shared vision stops the bug

https://github.com/CDeenen/SharedVision/assets/7229143/0471b023-2705-46b6-afb6-328f2aa2c192

**Console Log**
too many

**Comment by muhahahahe** [comment]
releasing tokens with a left click is a setting and needs to be activated in the core

![image](https://github.com/user-attachments/assets/5c3f8a7a-7041-4a6e-acfe-4a755fc2f326)

about the audio, can you give me more information about what audio (browser, foundry audio, ...)
maybe hit me up on discord, my username is muhahahahe my DMs are open

**Comment by jacksands** [comment]
Thank you for your answer, but the left click option is not the error in this case... I tried to make a video showing this.. sorry about my bad English...

v12 shared Vision error video
https://github.com/user-attachments/assets/a3890e81-03de-48a8-861f-876f983361f2

v11 working 
https://github.com/user-attachments/assets/49ed29bc-8ffd-4ada-9db3-e956f949441d


v12 console
Uploading v12 console.mp4…


I have not been able to reproduce the sound error to record, and I will try find you on discord as soon as I can!

tks once again!!

**Comment by MaterialFoundry** [comment]
This should be fixed in the latest version
